export const endpoints = {
  health: "/health",
  commandCenterFeed: "/api/command-center/feed",
  microsoftStatus: "/auth/microsoft/status",
  microsoftStart: "/auth/microsoft/start",
  microsoftDisconnect: "/auth/microsoft/disconnect",
  agentChat: "/agent/chat",
  toolsCatalog: "/api/tools/catalog",
  mailDraftReply: "/api/mail/draft-reply",
  mailDraftPreview: "/mail/drafts/preview",
  mailDraftCreate: "/mail/drafts",
  documentUpload: "/api/documents/uploads",
  documentAnalyze: "/api/documents/analyze",
  documentReports: "/api/documents/reports",
  approvals: "/approvals",
  approvalApprove: (approvalId: string) => `/approvals/${approvalId}/approve`,
  approvalReject: (approvalId: string) => `/approvals/${approvalId}/reject`,
};
