export const endpoints = {
  health: "/health",
  commandCenterFeed: "/api/command-center/feed",
  microsoftStatus: "/auth/microsoft/status",
  microsoftStart: "/auth/microsoft/start",
  microsoftDisconnect: "/auth/microsoft/disconnect",
  agentChat: "/agent/chat",
  toolsCatalog: "/api/tools/catalog",
  mailDraftReply: "/api/mail/draft-reply",
  mailDraftPreview: "/mail/drafts/preview",
  mailDraftCreate: "/mail/drafts",
  mailDraftSend: "/api/mail/drafts/send",
  documentUpload: "/api/documents/uploads",
  documentAnalyze: "/api/documents/analyze",
  documentReports: "/api/documents/reports",
  approvals: "/approvals",
  approvalApprove: (approvalId: string) => `/approvals/${encodeURIComponent(approvalId)}/approve`,
  approvalReject: (approvalId: string) => `/approvals/${encodeURIComponent(approvalId)}/reject`,
  automations: "/api/automations",
};
